# The config file needs to be named 'mysqldb_config.py'

host = '255.255.255.255'
username = 'someusername'
password = 'somepassword'
database = 'somedatabase'
clientes_table = 'clientes'
login_table = 'login'
login_radius_table = 'login_radius'
radius_acct_table = 'radius_acct'
radius_postauth_table = 'radius_postauth'
